In [1]:
# ==========================================================
# AI Diet Recommendation System
# Notebook 05 : Nutrition Engine
# ==========================================================

print("🥗 AI Diet Recommendation System")
print("Notebook 05 : Nutrition Engine")

🥗 AI Diet Recommendation System
Notebook 05 : Nutrition Engine

In [2]:
# ==========================================================
# Import Libraries
# ==========================================================

import os
import pandas as pd

In [3]:
# ==========================================================
# Project Path
# ==========================================================

PROJECT_PATH = os.path.abspath("..")

print(PROJECT_PATH)

C:\Users\Pranai Teja Sabbe\Desktop\AI_Diet_Project

In [4]:
# ==========================================================
# Nutrition Dataset Path
# ==========================================================

NUTRITION_PATH = os.path.join(
    PROJECT_PATH,
    "datasets",
    "nutrition",
    "nutrition_data"
)

print(NUTRITION_PATH)

C:\Users\Pranai Teja Sabbe\Desktop\AI_Diet_Project\datasets\nutrition\nutrition_data

In [5]:
# ==========================================================
# Load Nutrition Tables
# ==========================================================

food_df = pd.read_csv(
    os.path.join(NUTRITION_PATH, "food.csv")
)

food_nutrient_df = pd.read_csv(
    os.path.join(NUTRITION_PATH, "food_nutrient.csv"),
    low_memory=False
)

nutrient_df = pd.read_csv(
    os.path.join(NUTRITION_PATH, "nutrient.csv")
)

print("All Nutrition Tables Loaded Successfully!")

All Nutrition Tables Loaded Successfully!

In [6]:
print("Food Table :", food_df.shape)

print("Food Nutrient Table :", food_nutrient_df.shape)

print("Nutrient Table :", nutrient_df.shape)

Food Table : (87990, 5)
Food Nutrient Table : (170469, 11)
Nutrient Table : (477, 5)

In [7]:
# ==========================================================
# Important Nutrient IDs
# ==========================================================

IMPORTANT_NUTRIENTS = {

    1008: "Calories",
    1003: "Protein",
    1004: "Fat",
    1005: "Carbohydrates"

}

print(IMPORTANT_NUTRIENTS)

{1008: 'Calories', 1003: 'Protein', 1004: 'Fat', 1005: 'Carbohydrates'}

In [8]:
# ==========================================================
# Banana Food ID
# ==========================================================

food_id = 790774

print(food_id)

790774

In [9]:
# ==========================================================
# Get Nutrients for Banana
# ==========================================================

banana_nutrients = food_nutrient_df[

    food_nutrient_df["fdc_id"] == food_id

]

print("Total Nutrients Found :", len(banana_nutrients))

banana_nutrients.head(15)

Total Nutrients Found : 32

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired
94960,9638946,790774,1185,0.200,6.0,1.0,0.10,0.400,0.100,NaN,2019.0
94961,9638930,790774,1160,0.000,6.0,1.0,0.00,0.000,0.000,NaN,2019.0
94962,9638928,790774,1159,1.000,6.0,1.0,0.00,3.000,1.000,NaN,2019.0
94963,9638938,790774,1167,0.570,6.0,1.0,0.49,0.650,0.565,NaN,2019.0
94964,9638942,790774,1175,0.234,6.0,1.0,0.22,0.249,0.234,NaN,2019.0
94965,9638943,790774,1051,78.300,6.0,1.0,75.90,80.600,78.600,NaN,2019.0
94966,9638953,790774,1005,20.100,NaN,49.0,NaN,NaN,NaN,NaN,NaN
94967,9638933,790774,2029,0.000,6.0,1.0,0.00,0.000,0.000,NaN,2019.0
94968,9638937,790774,1176,0.000,6.0,1.0,0.00,0.000,0.000,NaN,2019.0
94969,9638936,790774,1002,0.120,6.0,1.0,0.10,0.150,0.110,NaN,2019.0
94970,9638954,790774,1106,1.000,NaN,49.0,NaN,NaN,NaN,NaN,NaN
94971,9638952,790774,1003,0.730,NaN,49.0,0.62,0.940,0.690,NaN,NaN
94972,9638947,790774,1184,0.000,6.0,1.0,0.00,0.000,0.000,NaN,2019.0
94973,9638949,790774,1032,279.000,4.0,1.0,250.00,333.000,266.000,NaN,2019.0
94974,9638955,790774,1008,85.000,NaN,49.0,NaN,NaN,NaN,NaN,NaN

In [10]:
# ==========================================================
# Keep Important Nutrients Only
# ==========================================================

banana_nutrients = banana_nutrients[

    banana_nutrients["nutrient_id"].isin(

        IMPORTANT_NUTRIENTS.keys()

    )

]

banana_nutrients

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired
94966,9638953,790774,1005,20.10,NaN,49.0,NaN,NaN,NaN,NaN,NaN
94971,9638952,790774,1003,0.73,NaN,49.0,0.62,0.94,0.69,NaN,NaN
94974,9638955,790774,1008,85.00,NaN,49.0,NaN,NaN,NaN,NaN,NaN
94977,9638935,790774,1004,0.22,6.0,1.0,0.10,0.38,0.20,NaN,2019.0

In [11]:
# ==========================================================
# Convert Nutrient IDs to Names
# ==========================================================

banana_nutrients["Nutrient"] = banana_nutrients["nutrient_id"].map(
    IMPORTANT_NUTRIENTS
)

banana_nutrients[
    [
        "Nutrient",
        "amount"
    ]
]

            Nutrient  amount
94966  Carbohydrates   20.10
94971        Protein    0.73
94974       Calories   85.00
94977            Fat    0.22

In [12]:
# ==========================================================
# Nutrition Dictionary
# ==========================================================

nutrition = {}

for _, row in banana_nutrients.iterrows():

    nutrition[row["Nutrient"]] = row["amount"]

nutrition

{'Carbohydrates': 20.1, 'Protein': 0.73, 'Calories': 85.0, 'Fat': 0.22}

In [13]:
# ==========================================================
# Display Nutrition Information
# ==========================================================

print("=" * 40)
print("🍌 Nutrition Information")
print("=" * 40)

print(f"Calories      : {nutrition['Calories']} kcal")
print(f"Protein       : {nutrition['Protein']} g")
print(f"Fat           : {nutrition['Fat']} g")
print(f"Carbohydrates : {nutrition['Carbohydrates']} g")

print("=" * 40)

========================================
🍌 Nutrition Information
========================================
Calories      : 85.0 kcal
Protein       : 0.73 g
Fat           : 0.22 g
Carbohydrates : 20.1 g
========================================

In [14]:
# ==========================================================
# Nutrition Function
# ==========================================================

def get_nutrition(food_id):

    # Step 1
    nutrients = food_nutrient_df[
        food_nutrient_df["fdc_id"] == food_id
    ]

    # Step 2
    nutrients = nutrients[
        nutrients["nutrient_id"].isin(
            IMPORTANT_NUTRIENTS.keys()
        )
    ]

    # Step 3
    nutrients["Nutrient"] = nutrients["nutrient_id"].map(
        IMPORTANT_NUTRIENTS
    )

    # Step 4
    nutrition = {}

    for _, row in nutrients.iterrows():

        nutrition[row["Nutrient"]] = row["amount"]

    return nutrition

In [15]:
banana_nutrition = get_nutrition(790774)

banana_nutrition

{'Carbohydrates': 20.1, 'Protein': 0.73, 'Calories': 85.0, 'Fat': 0.22}

In [16]:
print("=" * 45)
print("🍌 Banana Nutrition Information")
print("=" * 45)

for nutrient, value in banana_nutrition.items():

    if nutrient == "Calories":

        print(f"{nutrient:<15}: {value} kcal")

    else:

        print(f"{nutrient:<15}: {value} g")

print("=" * 45)

=============================================
🍌 Banana Nutrition Information
=============================================
Carbohydrates  : 20.1 g
Protein        : 0.73 g
Calories       : 85.0 kcal
Fat            : 0.22 g
=============================================

In [23]:
# ==========================================================
# Import Food Mapping Module
# ==========================================================

import sys
import os

sys.path.append(os.path.abspath("../app"))

from food_mapping import find_best_food

In [24]:
# ==========================================================
# Complete Nutrition Engine
# ==========================================================

def nutrition_engine(food_name):

    # Step 1
    best_food = find_best_food(food_name, food_df)

    # Step 2
    food_id = best_food["fdc_id"]

    # Step 3
    nutrition = get_nutrition(food_id)

    # Step 4
    result = {

        "Food Name": best_food["description"],

        "Food ID": food_id,

        "Nutrition": nutrition

    }

    return result

In [25]:
# ==========================================================
# Test Nutrition Engine
# ==========================================================

banana = nutrition_engine("banana")

banana

{'Food Name': 'Bananas, overripe, raw',
 'Food ID': np.int64(790774),
 'Nutrition': {'Carbohydrates': 20.1,
  'Protein': 0.73,
  'Calories': 85.0,
  'Fat': 0.22}}

In [26]:
# ==========================================================
# Display Nutrition Information
# ==========================================================

print("=" * 50)

print("🍌 Nutrition Information")

print("=" * 50)

print("Food Name :", banana["Food Name"])

print("Food ID   :", banana["Food ID"])

print()

for nutrient, value in banana["Nutrition"].items():

    if nutrient == "Calories":

        print(f"{nutrient:<15}: {value} kcal")

    else:

        print(f"{nutrient:<15}: {value} g")

print("=" * 50)

==================================================
🍌 Nutrition Information
==================================================
Food Name : Bananas, overripe, raw
Food ID   : 790774

Carbohydrates  : 20.1 g
Protein        : 0.73 g
Calories       : 85.0 kcal
Fat            : 0.22 g
==================================================