In [1]:
# ==========================================================
# AI Diet Recommendation System
# Notebook 06 : Recipe Engine
# ==========================================================

print("🍽 AI Diet Recommendation System")
print("Notebook 06 : Recipe Engine")

🍽 AI Diet Recommendation System
Notebook 06 : Recipe Engine

In [2]:
# ==========================================================
# Import Libraries
# ==========================================================

import os
import pandas as pd

In [3]:
# ==========================================================
# Project Path
# ==========================================================

PROJECT_PATH = os.path.abspath("..")

print(PROJECT_PATH)

C:\Users\Pranai Teja Sabbe\Desktop\AI_Diet_Project

In [4]:
# ==========================================================
# Recipe Dataset Path
# ==========================================================

RECIPE_PATH = os.path.join(
    PROJECT_PATH,
    "datasets",
    "recipes",
    "recipe_data"
)

print(RECIPE_PATH)

C:\Users\Pranai Teja Sabbe\Desktop\AI_Diet_Project\datasets\recipes\recipe_data

In [5]:
# ==========================================================
# Load Recipe Dataset
# ==========================================================

recipe_df = pd.read_csv(
    os.path.join(RECIPE_PATH, "RAW_recipes.csv")
)

print("Recipe Dataset Loaded Successfully!")

recipe_df.head()

Recipe Dataset Loaded Successfully!

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13
3,alouette potatoes,59389,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8

In [6]:
print("Recipe Dataset Shape")

recipe_df.shape

Recipe Dataset Shape

(231637, 12)

In [7]:
recipe_df.columns

Index(['name', 'id', 'minutes', 'contributor_id', 'submitted', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'ingredients',
       'n_ingredients'],
      dtype='object')

In [8]:
# ==========================================================
# Search Banana Recipes
# ==========================================================

banana_recipes = recipe_df[

    recipe_df["name"].str.contains(
        "banana",
        case=False,
        na=False
    )

]

print("Banana Recipes Found :", len(banana_recipes))

Banana Recipes Found : 3693

In [9]:
banana_recipes[
    [
        "name",
        "minutes",
        "n_ingredients"
    ]
].head(20)

,name,minutes,n_ingredients
8,bananas 4 ice cream pie,180,6
9,beat this banana bread,70,9
84,say what banana sandwich,5,3
90,spicy banana bread,75,11
95,the best banana bread or muffins,70,11
308,99 bananas foster oatmeal,10,9
464,mom s amazing banana bread,55,14
472,need a pick me up banana peanut butter smooth...,10,4
571,we re going bananas bread,72,10
662,modified banana bread by paula deen,60,11
695,guaranteed 5 star banana cake,60,9
727,tasty dish s banana pudding in 2 minutes,2,4
736,1 2 3 banana split ice cream cake,50,4
791,1 gram fat chocolate banana freezer pops,15,5
903,100 yummy banana bread,75,8
905,100 stroke banana bread,75,9
1035,1st place banana nut bread,80,11
1056,2 ingredients eggs banana pancakes,10,3
1065,2 minute low fat strawberry and banana custard...,2,5
1072,2 point banana muffins,25,9

============================================================
🍌 Banana Recipe Recommendations
============================================================

🍽 bananas 4 ice cream  pie
⏱ Cooking Time : 180 minutes
🥗 Ingredients : 6

🍽 beat this  banana bread
⏱ Cooking Time : 70 minutes
🥗 Ingredients : 9

🍽 say what   banana sandwich
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 3

🍽 spicy  banana bread
⏱ Cooking Time : 75 minutes
🥗 Ingredients : 11

🍽 the best  banana bread  or muffins
⏱ Cooking Time : 70 minutes
🥗 Ingredients : 11

🍽 99 bananas  foster oatmeal
⏱ Cooking Time : 10 minutes
🥗 Ingredients : 9

🍽 mom s amazing banana bread
⏱ Cooking Time : 55 minutes
🥗 Ingredients : 14

🍽 need a pick me up  banana peanut butter smoothie  no
⏱ Cooking Time : 10 minutes
🥗 Ingredients : 4

🍽 we re going bananas  bread
⏱ Cooking Time : 72 minutes
🥗 Ingredients : 10

🍽 modified  banana bread by paula deen
⏱ Cooking Time : 60 minutes
🥗 Ingredients : 11
============================================================

In [16]:
# ==========================================================
# Keep Recipes Between 5 and 60 Minutes
# ==========================================================

quick_recipes = banana_recipes[

    (banana_recipes["minutes"] >= 5) &
    (banana_recipes["minutes"] <= 60)

]

print("Quick Recipes Found :", len(quick_recipes))

quick_recipes[
    [
        "name",
        "minutes",
        "n_ingredients"
    ]
].head(20)

Quick Recipes Found : 2493

,name,minutes,n_ingredients
84,say what banana sandwich,5,3
308,99 bananas foster oatmeal,10,9
464,mom s amazing banana bread,55,14
472,need a pick me up banana peanut butter smooth...,10,4
662,modified banana bread by paula deen,60,11
695,guaranteed 5 star banana cake,60,9
736,1 2 3 banana split ice cream cake,50,4
791,1 gram fat chocolate banana freezer pops,15,5
1056,2 ingredients eggs banana pancakes,10,3
1072,2 point banana muffins,25,9
1330,3 ingredient cinnamon banana slice,5,3
1434,4 ingredient banana cake for two,20,4
1851,a berry good banana smoothie,10,4
1889,a different banana pound cake,60,6
1939,a friend of a friend of a friend s chocolate b...,60,13
1996,a little sweet banana dessert,30,8
2421,accra banana peanut cake ghana,60,11
2702,african banana coconut bake,10,6
2774,african spice rubbed drumsticks with banana boats,55,9
3239,ali s banana cakes,40,8

In [17]:
# ==========================================================
# Keep Recipes with <= 10 Ingredients
# ==========================================================

simple_recipes = quick_recipes[
    quick_recipes["n_ingredients"] <= 10
]

print("Simple Recipes Found :", len(simple_recipes))

simple_recipes[
    [
        "name",
        "minutes",
        "n_ingredients"
    ]
].head(20)

Simple Recipes Found : 1771

,name,minutes,n_ingredients
84,say what banana sandwich,5,3
308,99 bananas foster oatmeal,10,9
472,need a pick me up banana peanut butter smooth...,10,4
695,guaranteed 5 star banana cake,60,9
736,1 2 3 banana split ice cream cake,50,4
791,1 gram fat chocolate banana freezer pops,15,5
1056,2 ingredients eggs banana pancakes,10,3
1072,2 point banana muffins,25,9
1330,3 ingredient cinnamon banana slice,5,3
1434,4 ingredient banana cake for two,20,4
1851,a berry good banana smoothie,10,4
1889,a different banana pound cake,60,6
1996,a little sweet banana dessert,30,8
2702,african banana coconut bake,10,6
2774,african spice rubbed drumsticks with banana boats,55,9
3239,ali s banana cakes,40,8
3313,all bran banana bread,55,9
3741,almond flour banana pancakes,20,10
4034,almost chocolate no egg banana muffins,35,7
4043,almost fat free banana pudding,15,7

In [18]:
# ==========================================================
# Sort by Cooking Time and Ingredients
# ==========================================================

best_recipes = simple_recipes.sort_values(
    by=["minutes", "n_ingredients"],
    ascending=[True, True]
)

best_recipes[
    [
        "name",
        "minutes",
        "n_ingredients"
    ]
].head(20)

,name,minutes,n_ingredients
5318,anemic build your blood with honey and bananas,5,2
16669,banana milk raw dairy free,5,2
16806,banana on toast,5,2
49350,chocolate banana ice cream,5,2
78899,edible candles decoration for banana bread b...,5,2
88287,frozen bananas,5,2
94142,good for you banana choc chip ice cream,5,2
84,say what banana sandwich,5,3
1330,3 ingredient cinnamon banana slice,5,3
16065,banana grape smoothie,5,3
16074,banana ice cream dairy free,5,3
16093,banana and coconut,5,3
16100,banana and honey surprise,5,3
16435,banana coconut treat,5,3
16479,banana cream pi,5,3
16615,banana ice cream no machine needed,5,3
16668,banana milk,5,3
16706,banana nuggets,5,3
16764,banana nutella delight,5,3
16863,banana pepper spread,5,3

In [19]:
# ==========================================================
# Top 10 Recipe Recommendations
# ==========================================================

print("=" * 60)
print("🥗 Top Recommended Banana Recipes")
print("=" * 60)

for i, (_, row) in enumerate(best_recipes.head(10).iterrows(), start=1):

    print(f"\n{i}. {row['name'].title()}")

    print(f"⏱ Cooking Time : {row['minutes']} minutes")

    print(f"🥗 Ingredients : {row['n_ingredients']}")

print("=" * 60)

============================================================
🥗 Top Recommended Banana Recipes
============================================================

1. Anemic Build Your Blood With Honey And Bananas
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 2

2. Banana Milk  Raw  Dairy Free
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 2

3. Banana On Toast
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 2

4. Chocolate Banana Ice Cream
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 2

5. Edible Candles  Decoration For Banana Bread  Banoffee Cheesecake
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 2

6. Frozen Bananas
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 2

7. Good For You Banana Choc Chip Ice Cream
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 2

8. Say What   Banana Sandwich
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 3

9. 3 Ingredient Cinnamon Banana Slice
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 3

10. Banana   Grape Smoothie
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 3
============================================================

In [20]:
# ==========================================================
# Remove Less Healthy Recipes
# ==========================================================

UNHEALTHY_WORDS = [

    "cake",
    "cookie",
    "candy",
    "ice cream",
    "pie",
    "dessert",
    "frosting",
    "brownie",
    "chocolate",
    "cocktail"

]

healthy_recipes = best_recipes.copy()

for word in UNHEALTHY_WORDS:

    healthy_recipes = healthy_recipes[
        ~healthy_recipes["name"].str.contains(
            word,
            case=False,
            na=False
        )
    ]

print("Healthy Recipes Found :", len(healthy_recipes))

healthy_recipes[
    [
        "name",
        "minutes",
        "n_ingredients"
    ]
].head(20)

Healthy Recipes Found : 1317

                                                 name  minutes  n_ingredients
5318   anemic build your blood with honey and bananas        5              2
16669                    banana milk  raw  dairy free        5              2
16806                                 banana on toast        5              2
88287                                  frozen bananas        5              2
84                         say what   banana sandwich        5              3
1330               3 ingredient cinnamon banana slice        5              3
16065                         banana   grape smoothie        5              3
16093                              banana and coconut        5              3
16100                       banana and honey surprise        5              3
16435                            banana coconut treat        5              3
16479                                 banana cream pi        5              3
16668                                     banana milk        5              3
16706                                  banana nuggets        5              3
16764                          banana nutella delight        5              3
16863                            banana pepper spread        5              3
16869                     banana pina colada smoothie        5              3
16879                                      banana poi        5              3
16895         banana protein smoothie shake  ibs safe        5              3
16899                      banana pudding  raw recipe        5              3
16960                                    banana shake        5              3

In [21]:
# ==========================================================
# Top Healthy Banana Recipes
# ==========================================================

print("=" * 60)
print("🥗 Healthy Banana Recipe Recommendations")
print("=" * 60)

for i, (_, row) in enumerate(healthy_recipes.head(10).iterrows(), start=1):

    print(f"\n{i}. {row['name'].title()}")

    print(f"⏱ Cooking Time : {row['minutes']} minutes")

    print(f"🥗 Ingredients : {row['n_ingredients']}")

print("=" * 60)

============================================================
🥗 Healthy Banana Recipe Recommendations
============================================================

1. Anemic Build Your Blood With Honey And Bananas
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 2

2. Banana Milk  Raw  Dairy Free
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 2

3. Banana On Toast
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 2

4. Frozen Bananas
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 2

5. Say What   Banana Sandwich
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 3

6. 3 Ingredient Cinnamon Banana Slice
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 3

7. Banana   Grape Smoothie
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 3

8. Banana And Coconut
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 3

9. Banana And Honey Surprise
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 3

10. Banana Coconut Treat
⏱ Cooking Time : 5 minutes
🥗 Ingredients : 3
============================================================